name: CI tests

on: push

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04]

    steps:
    - uses: actions/checkout@master
    - name: Clone vader.vim
      run: git clone https://github.com/junegunn/vader.vim.git test/vader/vader.vim
    - name: Run Vader tests
      run: test/vader/run
