#!/usr/bin/env bash

check() {
   case $1 in
      *[0-9]':'[0-9]*) IFS=':' read -r -a k <<< "$1"
	 ((m=k0,s=k1,l=(m*60)+s)) ;;
      *[0-9]'m') l="$((${1%m}*60))" ;;
      *[0-9]'s') l="$((${1%s}))" ;;
      *) printf '\e[0;34m%s%s\n' "Usage: $(basename $0) "\
	 "[<number>m|s] [<min>:<sec>]"; exit 1
   esac
   l="$l-"
}

timer() { 
   st=$(date +%s)
   for ((;;)) do
      c=$(date +%s); sec=$(($l(c-st)))
      printf '\e[?25l\e[1;34m\r\e[J%02d:%02d' "$((sec/60))" "$((sec%60))"
      [[ $sec -lt "0" ]] && printf "\rtimes up!\n" && break
      sleep 1
   done
   [[ -f $(which beep) ]] && for ((i=0;i<4;i++)){ beep -D 20 -l 80;}
}

loop() { for ((;;)){ timer; printf '%s\e[1A' "[restart]";read;}; }

main() {
   trap "stty echo; printf '\e[J\e[?25h'" EXIT; stty -echo
   case $1 in "") timer ;; -l) check $2; loop ;; *) check $1; timer ;; esac
}

main "$@"
