#!/usr/bin/env bash

   #   _   _          ____                   __ _	  #
   #  | | | |        |___ \                 / _(_)	  #
   #  | |_| |__   ___  __) | ___ ___  _ __ | |_ _  __ _	  #
   #  | __| '_ \ / _ \|__ < / __/ _ \| '_ \|  _| |/ _` |  #
   #  | |_| | | |  __/___) | (_| (_) | | | | | | | (_| |  #
   #   \__|_| |_|\___|____/ \___\___/|_| |_|_| |_|\__, |  #
   #                                               __/ |  #
   #                                              |___/	  #


apps() {


   for a in autogap dunstbar dunst; do

      case $a in
	 dunstbar) 	o=(--boot) ;;
	 *) 		o=()
      esac

      if [[ $(ps ax | sed -n "/sed/d;/\<$a\>/p") ]]; then
	 ukill "$a" &>/dev/null && {
	    "$a" "${o[@]}" &>/dev/null & disown
	    printf '\e[33m%s: %s\n' "$a" "restarted"
	 } || printf '\e[31m%s: %s %s\n' "$a" "ukill" "failed"
      else
	 "$a" "${o[@]}" &>/dev/null & disown
	 printf '\e[37m%s: %s\n' "$a" "started"
      fi

   done

}


rules() {

   bspc rule -r Zathura
   bspc rule -a Zathura state=tiled

   bspc rule -r float
   bspc rule -a float sticky=off state=floating 

   bspc rule -r files
   bspc rule -a files locked=on sticky=on state=floating hidden=on

   bspc rule -r scratchterm
   bspc rule -a scratchterm locked=on sticky=on state=floating hidden=on

   bspc rule -r scratchmath
   bspc rule -a scratchmath locked=on sticky=on state=floating hidden=on

}


qute() {

   qute="$HOME/.config/qutebrowser"

   ln -sf "$HOME/.cache/wal/dunstrc" "$HOME/.config/dunst/dunstrc" &
   ln -sf "$HOME/.cache/wal/zathurarc" "$HOME/.config/zathura/zathurarc" &
   sassc "$qute/style.scss" > "$qute/style.css"

   sed 's/{color4}/'$color4'/p;s/{color2}/'$color2'/g;s/{color0}/'$color0'/g'\
      $HOME/.config/wal/qute >\
      $HOME/.config/qutebrowser/config.py

   #[[ ! -z $(pgrep -x qutebrowser) ]] && qutebrowser :config-source &>/dev/null

}


config() {

   bspc config focused_border_color "$color4"
   bspc config border_width         2
   bspc config split_ratio          0.5
   bspc config automatic_scheme spiral
   bspc config gapless_monocle true

   bspc monitor -d 1 2 3 4 5 6 7 8 9 10

   exec xmodmap -e "keycode 135 = Super_R"

}


main() {

   source "$HOME/.cache/wal/colors.sh"

   for fifo in $GAPFIFO $BARFIFO; do
      [[ -e "$fifo" ]] && rm "$fifo"; mkfifo "$fifo"
      bspc subscribe node_add node_remove desktop_focus > $fifo &
   done

   apps
   rules
   config
   qute

}

main
