#!/usr/bin/env bash
#
#   _   _          ____                   __ _
#  | | | |        |___ \                 / _(_)
#  | |_| |__   ___  __) | ___ ___  _ __ | |_ _  __ _
#  | __| '_ \ / _ \|__ < / __/ _ \| '_ \|  _| |/ _` |
#  | |_| | | |  __/___) | (_| (_) | | | | | | | (_| |
#   \__|_| |_|\___|____/ \___\___/|_| |_|_| |_|\__, |
#                                               __/ |
#                                              |___/


apps() {

   pkill dunst
   dunst & disown

   ukill acpid_events
   acpid_events & disown

   killall xbanish
   xbanish -i Mod1 -i Mod4 & disown

   pkill "compton"
   compton --dbus -b & disown

   ukill "autogap"
   ukill "dunstbar --boot"


   if [[ -z $(pgrep lemonbar) ]]; then

      autogap & disown
      dunstbar --boot & disown

      echo > $WMFIFO

   else

      ukill runbar &&
	 runbar & disown

      for i in {1..10}; do
	 bspc config -d $i left_padding 0
	 bspc config -d $i right_padding 0
	 bspc config -d $i window_gap 0
      done

   fi

}


rules() {

   bspc rule -r Zathura
   bspc rule -a Zathura state=tiled

   bspc rule -r float
   bspc rule -a float sticky=off state=floating 

   bspc rule -r files
   bspc rule -a files locked=on sticky=on state=floating hidden=on

   bspc rule -r scratchterm
   bspc rule -a scratchterm locked=on sticky=on state=floating hidden=on

   bspc rule -r scratchmath
   bspc rule -a scratchmath locked=on sticky=on state=floating hidden=on

}


colors() {

   source /home/ringdal/.cache/wal/colors.sh
   qute="$HOME/.config/qutebrowser"

   ln -sf "$HOME/.cache/wal/dunstrc" "$HOME/.config/dunst/dunstrc" &
   ln -sf "$HOME/.cache/wal/zathurarc" "$HOME/.config/zathura/zathurarc" &
   sassc "$qute/style.scss" > "$qute/style.css"

   sed 's/{color4}/'$color4'/p;s/{color2}/'$color2'/g;s/{color0}/'$color0'/g'\
      $HOME/.config/wal/qute >\
      $HOME/.config/qutebrowser/config.py

   [[ ! -z $(pgrep -x qutebrowser) ]] && qutebrowser :config-source

}


config() {

   bspc config focused_border_color "$color4"
   bspc config border_width         2
   bspc config split_ratio          0.5
   bspc config automatic_scheme spiral
   bspc config gapless_monocle true

   bspc monitor -d 1 2 3 4 5 6 7 8 9 10

   exec xmodmap -e "keycode 135 = Super_R"

}


main() {

   for fifo in $GAPFIFO $BARFIFO; do
      [[ -e "$fifo" ]] && rm "$fifo"; mkfifo "$fifo"
      bspc subscribe node_add node_remove desktop_focus > $fifo &
   done

   colors
   apps
   rules
   config

}

main
