#!/usr/bin/env bash

handler(){
   case "$1" in
      button/power) [[ $2 = "PBTN" ]] && "$HOME/.Scripts/byebye" ;;
      button/screenlock)
	 [[ $(<"$HOME/.keylock") = "enabled" ]] && {
	    xinput disable 'AT Translated Set 2 keyboard'
	    printf '%s' "disabled" > "$HOME/.keylock"
	    dunstify -r 10 -t 4000 "keyboard disabled"
	 } || {
	    xinput enable 'AT Translated Set 2 keyboard'
	    printf '%s' "enabled" > "$HOME/.keylock"
	    dunstify -r 10 -t 4000 "keyboard enabled"
	 }
	 ;;
      ac_adapter)
	 proc=$(ps -aux | sed -n "/vim/d;/ukill/d;/\<$app\>$/p" | awk '{print $2}')
	 [[ $2 = *ACPI* ]] && {
	    [[ ! -z $(pgrep lemonbar) && -e "/tmp/panel-fifo" ]] &&
	    echo "bat" > "/tmp/panel-fifo" || {
	    sleep .1; dunstbar; }; } ;;
   esac
}

main(){
   coproc acpi_listen
   trap 'kill $COPROC_PID' EXIT

   while read -u "${COPROC[0]}" -a event; do
      handler "${event[@]}"
   done
}

main
