#!/usr/bin/env bash
trap exit 0 EXIT
trap exit 0 KILL

if [ "$(pgrep -cx autogap)" -gt 1 ] ; then 
	killall autogap && exit 0
fi 

bspc subscribe | while read line; do
    W=$(bspc query -N -n .local.\!floating | wc -l)
    [[ "$W" -lt 2 ]] && P=80 || P=0
    bspc config left_padding $P
    bspc config right_padding $P
    G=$(echo "41 - ($W - 1) * 15" | bc)
    [[ "$G" -lt 1 ]] && G=1
    bspc config --desktop focused window_gap $G   
done
