#!/usr/bin/env bash

bspc subscribe node_add node_remove |
   while read line; do

      W=$(bspc query -N -n .local.\!floating | wc -l)
      (( W <= 1 )) && W=1

      (( G=26-(W-1)*(8+2/3) ))
      (( G <= 0 )) && G=0

      (( P=81-(W-1)*60 ))
      (( P <= 0 )) && P=0

      bspc config --desktop focused left_padding $P
      bspc config --desktop focused right_padding $P
      bspc config --desktop focused window_gap $G

   done
