#!/usr/bin/env bash

# ============= #
# == AWRSTRT == #
# ============= #

qutewal &

ln -sf "$HOME/.cache/wal/dunstrc" "$HOME/.config/dunst/dunstrc" &

ln -sf "$HOME/.cache/wal/colors.css" "$HOME/.config/qutebrowser/colors.css" &

#[[ $(pgrep -cx autogap) -gt 1 ]] && killall autogap || autogap

#autogap &

runbar &

# Compton
pkill compton
compton --dbus -b &

# Dunst
pkill dunst
dunst &
