#!/usr/bin/env bash

ask=$( echo -e "shutdown\nreboot\nlogout" | rofi -dmenu -i -p " power")

[[ $ask = "logout" ]] && sudo pkill Xorg
[[ $ask = "shutdown" ]] && shutdown now
[[ $ask = "reboot" ]] && reboot
