#!/usr/bin/env bash

ask=$( echo -e "Shutdown\nReboot\nKill Xorg" \
    | rofi -dmenu -i -p " Power")
#| dmenu -nf white -nb black -h 25 -b -i -p "Hvad vil du?:" ) 

[[ $ask = "Kill Xorg" ]] && pkill xinit
[[ $ask = "Shutdown" ]] && shutdown now
[[ $ask = "Reboot" ]] && reboot
