#!/usr/bin/env bash

current=$(awk -F/ 'NF>1{print $NF}' $HOME/.cache/wal/wal)
files=$(ls $HOME/Billeder/favoritter)

if [ $(echo "$files" | tail -1) = "${current}.sh" ]
then
    next="$(printf $files | head -1)"
else
    next=$(echo "$files" | awk "/$current/{getline; print}")
fi

$HOME/Billeder/favoritter/$next &
