#!/usr/bin/env bash

bar() { 
   sleep 1
   for ((;;)) do
      get; [[ $W != 0 ]] && clean && break
      dunstify "<b>$(date '+%R')</b>  |  $(i3network) | $(i3batt)"\
	 -t 10000 -r 90211
      sleep 5
   done
}

clean() { kill -9 $bar && dunstify -C 90211; }

get() { W=$(bspc query -N -n .local.\!floating | wc -l); }

main() {
   bspc subscribe node | while read line; do
	 get; clean; [[ $W == 0 ]] && bar & bar="$!"
      done
}

main
