#!/usr/bin/env bash

bar(){ for ((;;)){ barnot;sleep 5;}; }

barnot(){
   dunstify "$(i3batt) | $(i3network) | "\
      "<b>$(date '+%R')</b>" -t 5500 -r 90211
}

loop(){
   bspc subscribe node_add node_remove desktop_focus |
      while read line
      do
	 W=$(bspc query -N -n .local.\!floating | wc -l)
	 [[ $line != *remove* ]] && {
	    kill -9 $bar
	    dunstify -C 90211
	 }
	 (( W < 1 )) && sleep 1 && bar & bar="$!"
      done
}

main(){
   case $1 in
      -o) barnot ;;
      *) loop ;;
   esac
}

main "$@"
