#!/usr/bin/env bash

dir="$1"
file="$2"

printf "\e[H\e[2J\e[1;34mbackends:\n\e[0;34mw: wal\nc: colorz\n\
h: haishoku\nt: colorthief\n\n\e[1;32mchoose > \e[0m"

read -rsn1

case $REPLY in
    w) backend=wal ;;
    c) backend=colorz ;;
    h) backend=haishoku ;;
    t) backend=colorthief
esac

printf "\
    #\!/bin/sh\n\
    cp "$dir" ~/.config/wall.png\n\
    wal -tqi $dir --backend $backend\n\
    source /home/ringdal/.cache/wal/colors.sh\n\
    bspc config focused_border_color \$color4" >\
    $HOME/Billeder/favoritter/$file.sh

sudo chmod a+x ~/Billeder/favoritter/$file.sh
