#!/usr/bin/env bash

main(){
    rsync -ai --delete --dry-run $HOME/.config/{dunst,i3,nvim,qutebrowser,polybar,ranger,wal,compton.conf} ~/dotfiles/.config/
    rsync -ai --delete --dry-run $HOME/.Scripts $HOME/dotfiles/
    rsync -ai --delete --dry-run $HOME/{suckless,.latexmkrc,.nvimrc,.profile,.vimrc,.X.old,.xinitrc,.Xmodmap,.Xresources,.xsessionrc,.zprofile,.zsh_aliases,.zshrc} $HOME/dotfiles/
    stty -echo
    read -p "Commit to changes? (y/N)" a
    case $a in
	y) copy
	;;
	*) exit 0
	;;
    esac
}

copy(){
    rsync --delete -a $HOME/.config/{dunst,i3,nvim,qutebrowser,polybar,ranger,wal,compton.conf} ~/dotfiles/.config/
    rsync --delete -a $HOME/.Scripts $HOME/dotfiles
    rsync --delete -a $HOME/{suckless,.latexmkrc,.nvimrc,.profile,.vimrc,.X.old,.xinitrc,.Xmodmap,.Xresources,.xsessionrc,.zprofile,.zsh_aliases,.zshrc} $HOME/dotfiles/
    push
}

push(){
    cd ~/dotfiles/
    git add .
    git commit -a -m "I'm lazy"
    git push -u origin master
    stty echo
    exit 0
}
main
