#!/usr/bin/env bash
main(){
    rsync -ai --delete --dry-run $HOME/.config/{dunst,i3,nvim,qutebrowser,polybar,ranger,wal,compton.conf} ~/dotfiles/.config/
    rsync -ai --delete --dry-run $HOME/.Scripts $HOME/dotfiles/
    rsync -ai --delete --dry-run $HOME/{.apps,.latexmkrc,.nvimrc,.profile,.searched,.vimrc,.X.old,.xinitrc,.Xmodmap,.Xresources,.xsessionrc,.zprofile,.zsh_aliases,.zshrc} $HOME/dotfiles/
    stty -echo
    printf "Commit to changes? (y/N)"
    read -rsn1 a
    [[ $a == y ]] && copy || printf "\n" && exit
}

copy(){
    printf "\n"
    stty echo
    rsync --delete -a $HOME/.config/{dunst,i3,nvim,qutebrowser,polybar,ranger,wal,compton.conf} ~/dotfiles/.config/
    rsync --delete -a $HOME/.Scripts $HOME/dotfiles
    rsync --delete -a $HOME/{.apps,.latexmkrc,.nvimrc,.profile,.searched,.vimrc,.X.old,.xinitrc,.Xmodmap,.Xresources,.xsessionrc,.zprofile,.zsh_aliases,.zshrc} $HOME/dotfiles/
    push
}

push(){
    cd ~/dotfiles/
    git add .
    git commit -a -m "I'm lazy"
    git push -u origin master
    exit 0
}
[[ $1 == push ]] && push
[[ -z $1 ]] && main || printf "Unknown option: '$1'\n" && exit
