#!/usr/bin/env bash

percent="$(acpi -b | sed 's/,//g;s/://g;s/%//g' | awk '{print $4}')"
state="$(acpi -b | sed 's/,//g;s/://g;s/%//g' | awk '{print $3}')"

[[ $state = Discharging ]] && {
    [[ $percent -gt 80 ]] && state=""
    [[ $percent -le 80 ]] && state=""
    [[ $percent -le 65 ]] && state=""
    [[ $percent -le 35 ]] && state=""
    [[ $percent -le 15 ]] && state=""
    [[ $percent -le "15" ]] && out="$state  $percent%" || out="$state  $percent%"
}

[[ $state = Charging ]] && state="" && out="$state  $percent%"
[[ $state = Unknown ]] && state="" && out="$state  $percent%"
[[ $state = Full ]] && state="" && out="$state  $percent%"

printf '%s' " $out "
