#!/usr/bin/env bash

percent="$(acpi -b | sed 's/,//g;s/://g;s/%//g' | awk '{print $4}')"
state="$(acpi -b | sed 's/,//g;s/://g;s/%//g' | awk '{print $3}')"

[[ $state = Discharging ]] && {
    [[ $percent -gt 80 ]] && state=""
    [[ $percent -le 80 ]] && state=""
    [[ $percent -le 65 ]] && state=""
    [[ $percent -le 35 ]] && state=""
    [[ $percent -le 15 ]] && state=""
    #[[ $percent -le "15" ]] && out="%{F#f00}$state  $percent%%{F-}" || out="$state  $percent%"
    [[ $percent -le "15" ]] && out="<span color='#ff0000'>$state  $percent%</span>" || out="$state  $percent%"
}

#[[ $state = Charging ]] && state="" && out="%{F#0f0}$state  $percent%%{F-}"
#[[ $state = Unknown ]] && state="" && out="%{F#f0f}$state  $percent%%{F-}"
#[[ $state = Full ]] && state="" && out="%{F#0f0}$state  $percent%%{F-}"

[[ $state = Charging ]] && state="" && out="<span color='#00ff00'>$state  $percent%</span>"
[[ $state = Unknown ]] && state="" && out="<span color='yellow'>$state  $percent%</span>"
[[ $state = Full ]] && state="" && out="<span color='#00ff00'>$state  $percent%</span>"

echo " $out "
