#!/usr/bin/env bash

define() {
   case $inf in
      enp0s25) icon='' ;;
      wlp3s0) icon='' ;;
      *) icon='?'
   esac

   case $status in
      no-carrier) name='no connection' ;;
      routable) name="$(iwgetid -r)" ;;
      *) name="$status"
   esac
}

main() {
   status="$(networkctl status | grep State: | awk '{print $3}')"
   inf="$(networkctl status | grep Address |
      sed -n 's/Address://g;s/  *//g; s/on/ /g; P; Q' | awk '{print $2}')"

   define; printf '%s\n' "$icon $name"
}

main
