#!/usr/bin/env bash

status="$( networkctl status | grep State: | awk '{print $3}')"
ssid="$(iwgetid -r)"
if="$( networkctl status | grep Address | sed -n 's/Address://g;s/  *//g; s/on/ /g; P; Q' | awk '{print $2}' )"
	#ip="$( networkctl status | grep Address | sed -n 's/Address://g;s/  *//g; s/on/ /g; P; Q' | awk '{print $1}' )"

	[[ $if = wlp3s0 ]] && if=''
	[[ $if = enp0s25 ]] && if=''

	[[ $status = routable ]] && echo "$if $ssid" || echo -e "<span color='red'>  $status</span>"
	exit 0
