#!/usr/bin/env bash

volume="$(amixer get Master | sed -n '/Left:/g;s/\[//g;s/\]//p' | awk '{print $5}')"
[[ -z $(amixer get Master | grep -wo "on") ]] && state="mute" || state=" "

echo "$state $volume"
