#!/usr/bin/env bash
    source ~/.cache/wal/colors.sh
main(){
    #killall compton
    #scrot -e 'mv $f ~/scrot2.png' && compare scrot.png scrot2.png -compose src diff.png
    #compton --dbus -b
    #xwobf -s 2 -f ~/.wall.png
    scrot -z ~/.wall.png
    convert ~/.wall.png -scale 25% -scale 400% ~/.wall.png
    lock_
}

fade(){
    dis=$(echo -n "$DISPLAY" | tr -c '[:alnum:]' _)
    ifc='com.github.chjj.compton'
    obj='/com/github/chjj/compton'
    if [[ "$1" == "start" ]]; then
	dbus-send --print-reply --dest=$ifc.$dis \
	    $obj $ifc.opts_set string:fade_in_step double:0.025
	dbus-send --print-reply --dest=$ifc.$dis \
	    $obj $ifc.opts_set string:fade_out_step double:0.025
    else
	dbus-send --print-reply --dest=$ifc.$dis \
	    $obj $ifc.opts_set string:fade_in_step double:1
	dbus-send --print-reply --dest=$ifc.$dis \
	    $obj $ifc.opts_set string:fade_out_step double:1
    fi
}

lock_(){ 
	fade start 
	wrong=ff000099
	back=00000000
	fore=ffffff99
	#i3lock -e -i /tmp/.i3lock.png \
	i3lock -e -i ~/.wall.png \
	    --insidecolor=$back --ringcolor=$back --line-uses-inside \
	    --keyhlcolor=$back --bshlcolor=$back --separatorcolor=$back \
	    --insidevercolor=$back --insidewrongcolor=$back\
	    --ringvercolor=$back --ringwrongcolor=$back --verifcolor=00ff0099\
	    --greetertext="" --wrongcolor=$wrong \
	    --veriftext='verifying' --wrongtext='invalid passwd' \
	    --timecolor="$fore" --datecolor="$fore" --noinputtext='empty'\
	    --greetercolor=$fore --indpos="20:50" --greeterpos="80:50"\
	    --layout-align=1 --verif-align=1  --wrong-align=1
	while pgrep -x i3lock;do sleep .1;done
	sleep .4
    fade end
}
main
