#!/usr/bin/env bash

tomd(){
   case ${1##*.} in
      doc|pdf)
	 lowriter --convert-to docx "$1"
	 pandoc -t markdown "${1%.*}.docx" -o "${1%.*}.md"
	 rm "${1}x"
	 ;;
      docx) pandoc -t markdown "$1" -o "${1%.*}.md"
   esac
}

tex(){
   clean=( gnuploterrors log aux )
   pdflatex -shell-escape "$1"
   for ext in "${clean[@]}"; do
      rm "${1%.*}.$ext"
   done
}

main(){
   case $1 in
      -d) pandoc -t docx "$2" -o "${2%.*}.docx" ;;
      -o) [[ -r "${2%.*}.pdf" ]] && xdg-open "${2%.*}.pdf" & disown ;;
      -t) tex "$2" ;;
      --to-md) tomd "$2" ;;
      *) [[ -e $1 ]] && pandoc -V geometry:margin=1in -t latex "$1" -o "${1%.*}.pdf" ||
	 echo failed ;;
   esac
}

main "$@"
