#!/usr/bin/env bash

tomd(){
   case ${1##*.} in
      doc|pdf)
	 lowriter --convert-to docx "$1"
	 pandoc -t markdown "${1%.*}.docx" -o "${1%.*}.md"
	 rm "${1}x"
	 ;;
      docx) pandoc -t markdown "$1" -o "${1%.*}.md" ;;
      *) err="${1##*.}"; return 1
   esac
}

tex(){
   if [[ $(sed 1q $1) = "%math" ]]; then
      pdflatex -shell-escape "$1" 1>/dev/null
   else
      pdflatex -shell-escape "$1" 1>/dev/null
   fi

   clean=( gnuploterrors log aux )

   for ext in "${clean[@]}"; do
      [[ -f "${1%.*}.$ext" ]] && rm "${1%.*}.$ext"
   done
}

main(){
   case $1 in
      -d) pandoc -t docx "$2" -o "${2%.*}.docx" ;;
      -o) [[ -r "${2%.*}.pdf" ]] && xdg-open "${2%.*}.pdf" & disown ;;
      -t) tex "$2" ;;
      --to-md) tomd "$2" || echo "failed (can't convert $err to md)" ;;
      *) [[ -e $1 ]] && pandoc -V geometry:margin=1in -t latex "$1" -o "${1%.*}.pdf" || echo failed ;;
   esac
}

main "$@"
