#!/usr/bin/env bash

main (){
    trap 'bspc config top_padding 0' EXIT
    printbar
}

workspaces() {
    spaces=($(xprop -root _NET_DESKTOP_NAMES | awk '{$1=$2=""; print $0}' | sed -e 's/,//g' -e 's/\"//g' -e 's/^[[:space:]]*//'))
    current=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')

    for ((i=0;i<${#spaces[*]};i++)) do
        if [ "$i" = "$current" ]; then
            spaces[$i]="%{F#00ff00}  ${spaces[$i]}  %{B-}%{F-}"
        else
            spaces[$i]="${spaces[$i]}"
        fi
    done

    myspaces=$(sed -e 's/\(}\).?\(%\)/\1\2/' <<< "${spaces[*]}")
    printf "%s\n" "${myspaces}"
}

printbar (){
    while :;do
	input=" $(workspaces)%{r}"
	printf '%s\n' "$input"
	sleep .1
    done | lemonbar -p\
	-g 1366x23\
	-o 1\
	-B "#99000000"\
	#-f "Font Awesome:size=12"\
	#-f "SF Mono:size=10"
}
main
