#!/usr/bin/env bash

op="$1"

main(){
    [[ -z $op ]] && restartbar
    [[ $op == "toggle" ]] && togglebar
    [[ $op == "kill" ]] && killall -x polybar
}

togglebar(){ 
    [[ -z $(pgrep -x polybar) ]] && restartbar || killall -q polybar 
}

restartbar(){
    killall -q polybar
    while pgrep -u $UID -x polybar >/dev/null; do sleep 0.001; done
    polybar dummy &
    polybar example &
}
main
