#!/usr/bin/env bash

main(){
    [[ -z $1 ]] && restartbar
    [[ $1 == "toggle" ]] && togglebar
}

togglebar(){ 
    if [[ -z $(pgrep -x polybar) ]];then
	restartbar 
    else
	killall -q polybar 
	bspc config top_padding 0
	bspc config bottom_padding 0
    fi
}

restartbar(){
    killall -q polybar
    while pgrep -u $UID -x polybar >/dev/null; do sleep 0.001; done
    polybar hvadend 2>/dev/null &
    bspc config top_padding 23
}

main "$@"
