#!/usr/bin/env bash

id=$(xdotool search --class scratchterm)
st="st -c scratchterm -g 100x28+30+20 -e"

[[ ! -z "$id" ]] && bspc node "$id" --flag hidden -f
[[ -z "$id" ]] && {
   $st tmux new -s 'scratch' || $st tmux a -t '=scratch' 
}
