#!/usr/bin/env bash

main(){
id=$(xdotool search --class scratchterm)
opts=( -c scratchterm -g 100x28+30+20 -e )

[[ -z "$id" ]] && {
   st ${opts[@]} tmux new -s 'scratch' || st ${opts[@]} tmux a -t '=scratch' 
} || bspc node "$id" --flag hidden -f
}

main "$@"
