#!/usr/bin/env bash
sear="$(cat $HOME/.searched | head -7)"; ask="$(printf "$sear" | rofi -dmenu -i -p "Search")" 
#[[ -z $ask ]] || { printf "$ask\n$sear" > $HOME/.searched; sr $ask & disown;}
[[ -z $ask ]] || { printf "$ask\n$sear" > $HOME/.searched; surf duckduckgo.com/"$ask" & disown;}
