#!/usr/bin/env bash
# SIMPLE POMODORO TIMER

main() { 
	[[ -z $work ]] && echo "No time specified. Exiting." && exit
	((work*=60,notwork*=60)); start_work
}

start_work() {
	((t=1,st=$SECONDS))
	
	while [[ $t > 0 ]];do
		((t=(work-(SECONDS-st))))
		printf "\rwork: %02d:%02d" "$((t/60))" "$((t%60))"
		sleep 1
	done;play ~/.Scripts/.prokrastimer/gong.wav 2>/dev/null &
	read 2>/dev/null && start_notwork
}

start_notwork() {
	((t=1,st=$SECONDS));printf "\e[1A"
	while [[ $t > 0 ]];do
		((t=(notwork-(SECONDS-st))))
		printf "\rpaus: %02d:%02d" "$((t/60))" "$((t%60))"
		sleep 1
	done;play ~/.Scripts/.prokrastimer/gong.wav 2>/dev/null & 
	read 2>/dev/null && start_work
}
work=$1
notwork=$2
main
