#!/usr/bin/env bash

trap "tput cnorm;clear" EXIT
tput civis; printf '\e[1;34m'; clear

while :;do

    ((width=($(tput cols)-20)/2,rows=($(tput lines)-4)/2))

    out=$(figlet -cw $(tput cols) -f big $(printf '%02d:%02d' "$((SECONDS/60))" "$((SECONDS%60))"))

    printf '\e['$rows';0H\e[2J\r%s' "$out"
    sleep 1
done
