#!/usr/bin/env bash

day="$(date +%u)"
main() {
[[ $day == 7 ]] && today=sun tomorrow=mon
[[ $day == 6 ]] && today=sat tomorrow=sun
[[ $day == 5 ]] && today=fri tomorrow=sat
[[ $day == 4 ]] && today=thu tomorrow=fri
[[ $day == 3 ]] && today=wed tomorrow=thu
[[ $day == 2 ]] && today=tue tomorrow=wed
[[ $day == 1 ]] && today=mon tomorrow=tue
[[ $day == [1-4] ]] && [[ $(date +%H) < 16 ]] && format || exit
}

format() {
	firstString="$(gcalcli agenda $today $tomorrow --nocolor --calendar fili0514@vucfyn.net | sed -n 's/  */ /g;s/^ *//g;s/$ *//g;p')"
	secondString=""
	printf "${firstString//$(gcalcli agenda $today $tomorrow --nocolor --calendar fili0514@vucfyn.net\
		| sed -n 'n;p;q' | awk '{print $1" "$2" "$3" "}')/}" | awk '{print $1" "$4" "$5}'
}
main
