#!/usr/bin/env bash

theme() {

   #wal --theme base16-isotope &>/dev/null
   #wal --theme base16-gruvbox-hard &>/dev/null
   wal --theme base16-brewer &>/dev/null

}

on() {

   theme

   source /home/ringdal/.cache/wal/colors.sh

   ln -sf "$HOME/.cache/wal/dunstrc" "$HOME/.config/dunst/dunstrc" &
   feh --bg-fill "$HOME/Billeder/wallpapers/arch/black_arch.png"

   pkill dunst && dunst &>/dev/null & disown

   for i in {1..10}; do
      bspc config -d $i left_padding 0
      bspc config -d $i right_padding 0
   done

   runbar & disown

   $CONFIG &>/dev/null

   bspc config window_gap 1
   bspc config border_width 1

}

off() {

   ukill runbar
   pkill lemonbar

   bspc config top_padding 0

   chwal

   "$CONFIG" &>/dev/null
   sleep .1
   echo > "$GAPFIFO" &

}

case $1 in on) on ;; off) off; esac
